name: linguago_flutter
description: 'A new Flutter project.'

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.1.0
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.1.0
  bloc: ^9.2.1
  intl: ^0.20.2
  connectivity_plus: ^7.1.1
  dartz: ^0.10.1
  shared_preferences: ^2.5.5
  flutter_svg: ^2.3.0
  sqflite: ^2.4.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.15.0
  freezed: ^3.2.5

flutter:
  uses-material-design: true

  assets:
    # - assets/image/
